### PR TITLE
#159951950 unit tests for authentication functionality

### PR DESCRIPTION
**Pull request by byarustev**
#### What does this PR do?
adds unit tests for authentication functionality

#### Description of Task to be completed?
- test fields labels of user model
- ensure that user model methods are returning the right data
- test user registration
- test user login with valid data
- test user login with invalid data

#### How should this be manually tested?
switch to branch ch-project-unittests-159951950 
run command 
python manage.py test

#### What are the relevant pivotal tracker stories?
#159951950

### CODE REVIEW

**Comment by ruganda** [comment]
LGTM

**Comment by arthuroe** [comment]
@byarustev please resolve the conflicts below.

**Comment by arthuroe** [comment]
@byarustev status on this PR?

**Comment by byarustev** [comment]
i have accomplished this through PR #159951950 unittests for login and register

**Pull request closed without merging**
