### PR TITLE
#159951967 Users should be able to create/update/delete and retrieve articles

### PR DESCRIPTION
**Pull request by byarustev**
#### What does this PR do?
performs the CRUD operations for articles  
#### Description of Task to be completed?
has all the crud operations for articles end points working 
- article creation POST `/api/article/create`
- article deletion DELETE `/api/article/delete/article-slug`
- article updating PUT `/api/article/edit/article-slug`
- single article retrieval GET`/api/article/get/article-slug`
- all articles retrieval GET`/api/articles`
- adds tests for each of the above functionalities
#### How should this be manually tested?
- run the application on your machine and test each of the endpoints in postman 
- For example, to create an article. put *http://127.0.0.1:8000/api/article/create* in post man 
 
``` 
{
  "title":"this is my title njd",  
  "description":"this is a description",  
  "body":"this is the body"  
}
```
#### What are the relevant pivotal tracker stories?
#159951967

### CODE REVIEW

**Comment by marthamareal** [comment]
@byarustev also in the PR on testing manually can you put a sample of an article we put in postman

**Comment by marthamareal** [comment]
@byarustev 

- It would be better not to include the apps folder in settings.py
- In urls of get/,edit/,delete we can use an articles id instead of slug
- Also the path to all articles, django structure is urls end with a / , and instead of using all you can use articles to mean may and article for one (articles/ and article/<int:id>/)

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by ruganda** [comment]
LGTM

**Comment by byarustev** [comment]
> @byarustev
> 
> * It would be better not to include the apps folder in settings.py
> * In urls of get/,edit/,delete we can use an articles id instead of slug
> * Also the path to all articles, django structure is urls end with a / , and instead of using all you can use articles to mean may and article for one (articles/ and article/int:id/)

Thanks, Martha for the feedback.
- I have removed the apps folder from settings.py 
- for the point of using IDs, I have read about the advantages of using slugs than ids and slugs outweigh ids.  one of them is for search engine optimizations where articles with slugs have a better chance than those with just ids in their urls.
- I have also worked on the /articles url to return all articles

**Pull request merged**
