### PR TITLE
#159951967 Users should be able to create/update/delete and retrieve articles

### PR DESCRIPTION
**Pull request by byarustev**
#### What does this PR do?
performs the CRUD operations for articles  
#### Description of Task to be completed?
has all the crud operations for articles end points working 
- article creation POST `/api/article/create`
- article deletion DELETE `/api/article/delete/article-slug`
- article updating PUT `/api/article/edit/article-slug`
- single article retrieval GET`/api/article/get/article-slug`
- all articles retrieval GET`/api/articles`
- adds tests for each of the above functionalities
#### How should this be manually tested?
- run the application on your machine and test each of the endpoints in postman 
- For example, to create an article. put *http://127.0.0.1:8000/api/article/create* in postman 
 
``` 
{
  "title":"this is my title njd",  
  "description":"this is a description",  
  "body":"this is the body"  
}
```
#### What are the relevant pivotal tracker stories?
#159951967

Co-authored-by: Isaac Owomugisha <archimedesisaac@gmail.com>

### CODE REVIEW

**Comment by marthamareal** [comment]
@byarustev 
- It would be better for you to validate who edits an article.
- And also on returning the list, can you add a key to show that they are articles.

**Comment by byarustev** [comment]
> @byarustev
> 
> * It would be better for you to validate who edits an article.
> * And also on returning the list, can you add a key to show that they are articles.

validation sorted thanks for the feedback

**Comment by arthuroe** [comment]
@byarustev I missed this the first time, but can you shorten the commit message.

**Comment by ruganda** [comment]
LGTM

**Comment by byarustev** [comment]
> @byarustev I missed this the first time, but can you shorten the commit message.

i have worked on this

**Comment by cmplx-xyttmt** [comment]
LGTM

**Pull request merged**
