### PR TITLE
#159951968 Rate user articles

### PR DESCRIPTION
**Pull request by marthamareal**
#### What does this PR do?
- Enables users to rate articles for different aurthors
#### Description of Task to be completed?
- provide data for rating an article
- validate the data provided
- rate the article if data is valid
- test different scenarios when rating an article
#### How should this be manually tested?
Run the project on your machine
go postman on and post the data below to this url  `http://127.0.0.1:8000/api/article/rating/`
```
{
    	"article":"this-is-updated-title-njd", // this is a slug of an article
    	"rating":3
    
}
```
#### What are the relevant pivotal tracker stories?
#159951968

### CODE REVIEW

**Comment by cmplx-xyttmt** [comment]
@marthamareal, how will a user be able to see the average rating of their article? (that's one of the acceptance criteria on the pivotal tracker story)

**Comment by ruganda** [comment]
Other than @cmplx-xyttmt's comment, LGTM

**Comment by byarustev** [comment]
> @marthamareal, how will a user be able to see the average rating of their article? (that's one of the acceptance criteria on the pivotal tracker story)

i think this should be done in the article serializer. you can overide the to_representaion method and you also include the average of the rating

**Comment by marthamareal** [comment]
> > @marthamareal, how will a user be able to see the average rating of their article? (that's one of the acceptance criteria on the pivotal tracker story)
> 
> i think this should be done in the article serializer. you can overide the to_representaion method and you also include the average of the rating

yes i have done that average_rating is a dynamic property to article

**Comment by ruganda** [comment]
LGTM

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by byarustev** [comment]
LGTM

**Pull request merged**
