### PR TITLE
#159951950 unittests for login and register

### PR DESCRIPTION
**Pull request by byarustev**
#### What does this PR do?
adds unit tests for authentication functionality
#### Description of Task to be completed?
* test user registration
* test user login with valid data
* test user login with invalid data
#### How should this be manually tested?
- run `python manage.py test`
#### What are the relevant pivotal tracker stories?
#159951950

### CODE REVIEW

**Comment by marthamareal** [comment]
LGTM

**Comment by arthuroe** [comment]
@byarustev can we format the text in the `PR` appropriately.

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by ruganda** [comment]
LGTM

**Pull request merged**
