### PR TITLE
#159951974 Implement searching and filtering based on parameters

### PR DESCRIPTION
**Pull request by ruganda**
#### What does this PR do?
- Implement searching and filtering based on parameters
#### Description of Task to be completed?
- To enable filtering based on parameters like the author, title and slug
- To enable searching of title, slug and author
#### How should this be manually tested?
- To `search`, access the endpoint `api/articles/search/` , `GET` , and search for either the title,slug or author for example `api/articles/search/?search=politics-is-shit-1`
screen shot 2018-09-16 at 20 32 42

-  To`filter`, access the endpoint `api/articles/search/` , `GET` , and filter by either the title,slug or author for example `api/articles/search/?author=ruganda`
screen shot 2018-09-16 at 20 38 33
####  What are the relevant pivotal tracker stories?
 
#159951979

### CODE REVIEW

**Comment by marthamareal** [comment]
@ruganda  change the story id in your commit and PR title.

**Comment by byarustev** [comment]
@ruganda coverage is reducing, you will need to test fully the new code

**Comment by byarustev** [comment]
@ruganda You have some conflicts

**Comment by marthamareal** [comment]
@ruganda  squash your commits and conflicts

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by marthamareal** [comment]
LGTM

**Comment by byarustev** [comment]
LGTM

**Pull request merged**
