### PR TITLE
#159951974  Send notifications to users

### PR DESCRIPTION
**Pull request by marthamareal**
#### What does this PR do?
- Enables users to get notifications
  - when users they follow publish new articles
  - when articles in their favorites get comments

#### Description of Task to be completed?
- Subscribes users to receive notifications
- Creates notifications on the publishing of an article and commenting on an article
- Sends notifications to users via email and application
- Enable users to unsubscribe/subscribe for notifications
- Send emails through an automated task

#### How should this be manually tested?

- run the application  and with a method PUT
- use  `http://127.0.0.1:8000/api/notifications/by_email/True` to subscribe for notifications by email
- use `http://127.0.0.1:8000/api/notifications/by_email/False` to unsubscribe for notifications by email
- use `http://127.0.0.1:8000/api/notifications/by_app/True` to subscribe for notifications by app
- use `http://127.0.0.1:8000/api/notifications/by_app/False` to unsubscribe for notifications by app

What are the relevant pivotal tracker stories?
#159951974

Co-authored-by: Byarugaba Stephen <byarus45@gmail.com>

### CODE REVIEW

**Comment by ruganda** [comment]
@marthamareal, I appreciate the fact that you have been able to finish this task in time. Your implementation is good, But you could do better by adding more tests so that test coverage doesn't drop on your PR.

**Comment by byarustev** [comment]
by_appl - i think this is a typo in your PR description

**Comment by byarustev** [comment]
> by_appl - i think this is a typo in your PR description
i have edited the description dont mind this for now

**Comment by marthamareal** [comment]
> by_appl - i think this is a typo in your PR description

yes Fixed thanks

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by byarustev** [comment]
LGTM

**Pull request merged**
