### PR TITLE
feature(Tagging) Implement tagging an article

### PR DESCRIPTION
**Pull request by ruganda**
#### What does this PR do?
- implements tagging of an article
#### Description of Task to be completed?
- To ensure a tag is created on an article
- To retrieve all the existing tags
#### How should this be manually tested?
- access `api/article/create` , `POST` and add tags in the request body with the key `"tags"`and `values` as a string of tags separated by commas as shown in the screenshots.
- To retrieve tags access `api/article/tags` `GET`

#### request
screen shot 2018-09-19 at 12 38 42

####  Response
screen shot 2018-09-18 at 19 07 41

####  List of Tags
screen shot 2018-09-18 at 19 08 07
####  What are the relevant pivotal tracker stories?

-  #159951976

### CODE REVIEW

**Comment by byarustev** [comment]
@ruganda migrations are causing code climate issues.

**Comment by marthamareal** [comment]
LGTM

**Comment by byarustev** [comment]
LGTM

**Comment by cmplx-xyttmt** [comment]
LGTM

**Pull request merged**
