### PR TITLE
#159951960 integrate test coverage 

### PR DESCRIPTION
**Pull request by ruganda**
#### What does this PR do?
Integrate code coverage.

#### Description of Task to be completed?
- The application should have automatic code coverage
#### How should this be manually tested?
- Click on the coveralls badge and view the build
#### What are the relevant pivotal tracker stories?
#159951960

### CODE REVIEW

**Comment by arthuroe** [comment]
@ruganda resolve the conflicts below and squash your commits.

**Comment by arthuroe** [comment]
@ruganda  when you look at your `PR` title and the rest, do you see a difference?

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by byarustev** [comment]
LGTM

**Comment by marthamareal** [comment]
LGTM

**Pull request merged**
