### PR TITLE
Ch switch to postgesql db 159951958

### PR DESCRIPTION
**Pull request by ruganda**
#### What does this PR do?
Switches the database engine to PostgreSQL.
#### Description of Task to be completed?
- The application should be able to use postgreSQL while in development, testing and production environments
#### How should this be manually tested?
- clone the github repo
- create a databases with names `'ah_database'` and `'ah_test_db'` in postgres.
-  Provide  your database password in `settings.py`
-  cd into the repo and make migrations.
- You should be able to see the tables in your postgres database
#### What are the relevant pivotal tracker stories?
#159951958

### CODE REVIEW

**Comment by byarustev** [comment]
LGTM

**Comment by arthuroe** [comment]
@ruganda this PR is supposed to contain only changes for Postgres DB, but I see changes similar to @marthamareal's PR. Ensure you make the changes required for the task assigned to you only. If you require changes from another PR, wait for it to be merged.

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by arthuroe** [comment]
@ruganda resolve these conflicts, they are a testimony of the issue I pointed out in my earlier comment.

**Pull request closed without merging**
