### PR TITLE
#160131842 Link Travis CI with Slack

### PR DESCRIPTION
**Pull request by marthamareal**
#### What does this PR do?
configures Travis CI to post notifications in slack channel
#### Description of Task to be completed?
- add travis CI in the apps of the slack channel
- edit travis.yml for notifications
#### What are the relevant pivotal tracker stories?
#160131842

### CODE REVIEW

**Comment by arthuroe** [comment]
@marthamareal add a new line at the end of the file.

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by arthuroe** [comment]
LGTM

**Comment by byarustev** [comment]
LGTM

**Comment by ruganda** [comment]
LGTM

**Pull request merged**
