### PR TITLE
#160649969 Ensure that tags can be updated on updating an article

### PR DESCRIPTION
**Pull request by ruganda**
#### What does this PR do ?
- Ensure that tags can be updated on updating an article
#### Description of Task to be completed?
- To fix updating tags on an article
#### How should this be manually tested?
access `api/article/edit/<slug>` and update the tags
#### What are the relevant pivotal tracker stories?
 #160649969

### CODE REVIEW

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by marthamareal** [comment]
@ruganda Thank you for recognizing this bug in our system and acting on it, however, there are some few points you can consider to make the fix better.
- What happens if a user who is not the author updates the article (raise exception with status_code 403)
- Also if the author updates other fields and not tags. the update function will automatically remove the tags

**Comment by ruganda** [comment]
@marthamareal , Thanks for the feedback, I appreciate that you were able to point out those key points, but **(raising an exception with status_code 403)** is out of the scope for this PR, as you realize that it is not among the changed lines.
-  if the author updates other fields and not tags. the update function will **NOT** automatically remove the tags
Thanks for the feedback

**Comment by marthamareal** [comment]
LGTM

**Pull request merged**
