### PR TITLE
#159951952 Upgrade From Django 1.10 to Django 2.1

### PR DESCRIPTION
**Pull request by marthamareal**
### **What does this PR do?**

- Upgrade Authors Haven Django app from Django 1.10 to Django 2.1

### **Description of Task to be completed?**

- add relevant versions of Django and other tools in requirements
- makemigrations of the authentication app

### **How should this be manually tested?**

- clone the repository, cd into it, and run `python manage.py runserver`

#### **What are the relevant pivotal tracker stories?**

- #159951952

### CODE REVIEW

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by arthuroe** [comment]
@marthamareal given we are upgrading to Django 2, let's also use it's URL formats and deprecate the ones for Django 1.11.

**Comment by ruganda** [comment]
LGTM

**Comment by byarustev** [comment]
LGTM

**Pull request merged**
